.PHONY: install render preview update-extension update-template

install:
	quarto add fs-ise/quarto-template-presentation --no-prompt

render:
	quarto render

preview:
	quarto preview presentation.qmd

update-extension:
	quarto update extension fs-ise/quarto-template-presentation

update-template:
	copier update --trust
