/*
 * Simplemenu for Reveal.js
 * Copyright (c) Martin Donath; distributed under the MIT license.
 */
var Simplemenu = (function () {
  "use strict";

  function init(deck) {
    var options = deck.getConfig().simplemenu || {};
    var reveal = document.querySelector(".reveal");
    var barhtml = options.barhtml || {};
    if (reveal && barhtml.header) {
      reveal.insertAdjacentHTML("afterbegin", barhtml.header);
    }
    if (reveal && barhtml.footer) {
      reveal.insertAdjacentHTML("beforeend", barhtml.footer);
    }
    var bars = document.querySelectorAll(".menubar");
    if (!bars.length) return;

    /* Quarto puts data-stack-name on the outer section generated by a level-1
       heading. Reading those stacks keeps horizontal menu links and vertical
       Reveal navigation in sync without cloning slide content. */
    var groups = Array.prototype.slice.call(
      document.querySelectorAll(".reveal .slides > section[data-stack-name]")
    );

    bars.forEach(function (bar) {
      if (options.scale) bar.style.fontSize = options.scale + "em";
      var menu = bar.querySelector(".menu");
      if (!menu) return;
      menu.replaceChildren();
      groups.forEach(function (section) {
        var item = document.createElement("li");
        var link = document.createElement("a");
        var indices = deck.getIndices(section);
        link.textContent = section.dataset.stackName;
        link.href = "#/" + indices.h;
        link.dataset.simplemenuTarget = String(indices.h);
        item.appendChild(link);
        menu.appendChild(item);
      });
    });

    function update(event) {
      var current = event && event.currentSlide;
      var indices = current ? deck.getIndices(current) : null;
      document.querySelectorAll("[data-simplemenu-target]").forEach(function (link) {
        var active = Boolean(indices && link.dataset.simplemenuTarget === String(indices.h));
        link.parentElement.classList.toggle("active", active);
        link.setAttribute("aria-current", active ? "true" : "false");
      });
      document.querySelectorAll(".menubar .menu-slide-number").forEach(function (number) {
        number.textContent = (deck.getSlidePastCount() + 1) + " / " + deck.getTotalSlides();
      });
    }

    deck.on("ready", update);
    deck.on("slidechanged", update);
    update({ currentSlide: deck.getCurrentSlide() });
  }

  return { id: "simplemenu", init: init };
})();
